name: Test

on:
  push:

concurrency:
  group: test

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: python3 -m pip install aiodocker
      - run: python3 run.py
      - run: docker system df
      - run: docker images

      - uses: bowtie-json-schema/bowtie@main
      - run: bowtie suite -i ts-vscode-json-languageservice  https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/main/tests/draft6 || true
      - run: docker system df
        if: always()
      - run: docker images
        if: always()
